
kind: pipeline
name: default
type: kubernetes
steps:
  - name: install
    image: node:14
    environment:
      NPM_AUTH_USERNAME:
        from_secret: npm_auth_username
      NPM_AUTH_TOKEN:
        from_secret: npm_auth_token
    commands:
      - npm ci
  - name: test
    image: node:14
    environment:
      NPM_AUTH_USERNAME:
        from_secret: npm_auth_username
      NPM_AUTH_TOKEN:
        from_secret: npm_auth_token
    commands:
      - npm --version
      - npm ls eslint-plugin-filenames
      - ls -la node_modules/ | grep eslint
      - npm test
  - name: publish
    image: node:14
    environment:
      NPM_AUTH_USERNAME:
        from_secret: npm_auth_username
      NPM_AUTH_TOKEN:
        from_secret: npm_auth_token
    commands:
      - npm publish
    when:
      event:
        - tag
